### ISSUE TITLE
Release Checklist CEP18 v1.0

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/erc20#78]
- [x]  (DEV) Close or defer all tickets in the epics (code complete/scope closure) - code freeze
- [x]  (DEV) Create release candidate branch (branching, tagging)
- [ ]  (Business Owner) Identify destination & distribution targets (communications, announcements)
- [x]  (SRE) Ensure SRE pipelines are in place
- [x]  (DEV) unit & Integration tests have passed
- [x]  (DEV) Create readme in git repo (scope closure)
- [x]  (DEV) ensure changelog is in place
- [x]  (SRE) acceptance tests in a production environment has passed
- [x]  (DEV) Documentation updates are in place (docs team)

**Comment by cspramit** [comment]
Note: Since this is v1.0 - the change log is empty
